language: go

branches:
  only:
    - master

matrix:
  include:
    - go: 1.9.x
  
cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

before_install:
  - cp config.example.yml config.yml

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - export CI=TRAVIS

script:
  - "go vet ./...",
  - go test -v ./...