language: go

branches:
  only:
    - ci

matrix:
  include:
    - go: 1.9.x
  
cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

before_install:
  - cp config.example.yml config.yml

install:
  - go get github.com/modocache/gover
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - export CI=TRAVIS

script:
  - "go vet ./..."
  - go test -v ./...
  # Collect coverage reports
  - go list -f '{{if len .TestGoFiles}}"go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' ./... | xargs -i sh -c {}
  # Merge coverage reports
  - gover . coverprofile.txt

after_success:
  # Send coverage reports to Codecov
  - bash <(curl -s https://codecov.io/bash) -f coverprofile.txt