feeds:
  - https://medium.com/feed/tag/programming

tags:
  - go

store:
  bolt:
    file: /rfeed/db/bolt.db

check_interval: 60

slack:
  token: slack-token
  channel: slack-channel

telegram:
  token: telegram-token
  chat_id: telegram-chat_id
