[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/grokify/html-strip-tags-go"

[[constraint]]
  name = "github.com/mmcdole/gofeed"
  version = "1.0.0-beta"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"
